stages:
  - run

# setup:
#   stage: setup
#   tags:
#     - cisco-ansible
#   script:
#     - cd ./ios-xe-csr-recommended/
#     - virtualenv .venv
#     - source .venv/bin/activate
#     - pip install -r requirements.txt

test:
  # image: python:3.11.4-alpine3.18
  image: python:3.11.2
  stage: run
  tags:
    - cisco-ansible
  script:
    - pip install virtualenv
    - cd ./ios-xe-csr-recommended/
    - virtualenv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - ansible-playbook playbooks/show_facts.yaml
  # script:
  #   - cd ./ios-xe-csr-recommended/
  #   - virtualenv .venv
  #   - source .venv/bin/activate
  #   - pip install -r requirements.txt
  #   - ansible-playbook playbooks/show_facts.yaml

