stages:
  - run

test:
  stage: run
  tags:
    - cisco-ansible
  script:
    - pwd
    - cd ./ios-xe-csr-recommended/
    - source .venv/bin/activate
    - ansible-playbook playbooks/show_facts.yaml

