stages:
  - setup
  - run

setup:
  stage: setup
  tags:
    - cisco-ansible
  script:
    - cd ./ios-xe-csr-recommended/
    - virtualenv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt

test:
  stage: run
  tags:
    - cisco-ansible
  script:
    - ansible-playbook playbooks/show_facts.yaml

