stages:
  - run

test:
  stage: run
  tags:
    - cisco-ansible
  script:
    - source ~/lcrosendo_projects_ansible/ios-xe-csr-recommended/.venv/bin/activate
    - ~/lcrosendo_projects_ansible/ios-xe-csr-recommended/ansible-playbook playbooks/show_facts.yaml

