stages:
  - Build
  - Test

Build:
  stage: Build
  image: hikiko999/ansible_python:python-3.11.2
  tags:
    - cisco-ansible
  script: 
    - chmod 755 .
    - ansible-playbook playbooks/build.yml
  artifacts:
    paths:
      - outputs/*

Test:
  stage: Test
  variables:
    DEST_IP_VAR: 5.10.15.20,10.20.30.40
  trigger:
    project: lcrosendo/devnet-pyats-ios-xe-csr
    strategy: depend
