stages:
  - Build
  - Test

Build:
  stage: Build
  image: hikiko999/ansible_python:python-3.11.2
  tags:
    - cisco-ansible
  script: 
    - chmod 755 .
    - ansible-playbook playbooks/build.yml
  artifacts:
    paths:
      - outputs/*

Test:
  stage: Test
  trigger:
    project: lcrosendo/devnet-pyats-ios-xe-csr
