stages:
  - Build
  - Backup
  - Test

Build:
  stage: Build
  environment: Building
  image: hikiko999/ansible_python:python-3.11.2
  tags:
    - docker-ansible
  script: 
    - chmod 755 .
    - ansible-playbook playbooks/build.yml
  artifacts:
    paths:
      - outputs/*

Backup:
  stage: Backup
  environment: Backup
  tags:
    - shell-aws
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - aws s3 sync outputs s3://$S3_BUCKET/$CI_PROJECT_NAME/ #$CI_PIPELINE_CREATED_AT/

Test:
  stage: Test
  variables:
    DEST_IP_VAR: 5.10.15.20,10.20.30.40
  trigger:
    project: lcrosendo/devnet-pyats-ios-xe-csr
    strategy: depend