stages:
  - run

test:
  stage: run
  tags:
    - cisco-ansible
  script:
    - source ./ios-xe-csr-recommended/bin/activate
    - ./ios-xe-csr-recommended/ansible-playbook playbooks/show_facts.yaml

