---
  - name: GATHER FACTS FROM CISCO ROUTER
    hosts: ios_xe
    connection: network_cli
    gather_facts: no

    tasks:
      - name: GATHER FACTS
        ios_facts:
        register: output

      - name: VIEW DATA
        debug:
          var: output
      
      - name: CREATES OUTPUT FOLDER
        file:
          path: "outputs"
          state: directory
          mode: 0775
        run_once: true

      - name: SAVE DATA
        copy:
          content: "{{ output }}"
          dest: "outputs/{{ inventory_hostname }}.txt"
          mode: 0664
