---
  - name: SHOW IP INTERFACES
    hosts: ios_xe
    connection: network_cli
    gather_facts: no

    tasks:
      - name: SHOW IP INT BRIEF COMMAND
        ios_command:
          commands: 
            - show ip int brief
        register: output
      
      - name: RESULT IP INT BRIEF
        debug: 
          var: output['stdout']