---
# tasks file for basic-config
- name: CREATE CONFIGURATION OUTPUT PATHS
  set_facts:
    old_config_path: "../outputs/{{ inventory_hostname }}/old/{{ ansible_date_time.iso8601 }}_{{ inventory_hostname }}"
    new_config_path: "../outputs/{{ inventory_hostname }}/new/{{ ansible_date_time.iso8601 }}_{{ inventory_hostname }}"

- name: GATHER OLD CONFIG
  cisco.ios.ios_facts:
    gather_subset: config
  register: old_config

- name: SHOW OLD CONFIG
  debug:
    msg: "{{ old_config }}"

- name: SAVE OLD CONFIG
  copy:
    content: "{{ old_config }}"
    destination: "{{ old_config_path }}"
    mode: 0664

- name: SHOW PRE CONFIG
  debug:
    msg: "{{ lookup('template', 'templates/config_pre.j2') }}"

# PROMPT HERE FOR CHANGE

- name: CHANGE HOSTNAME
  include_tasks:
    file: change_hostname.yml
  when: "{{ configuration['dev_hostname'] }}" is defined

- name: CHANGE INTERFACE
  include_tasks:
    file: change_interface.yml
  when: "{{ configuration['dev_interfaces'] }}" is defined

- name: SAVE NEW CONFIG
  template:
    src: "{{ lookup('template', 'templates/config_post.j2') }}"
    dest: "{{ new_config_path }}"
    mode: 0664