---
  - name: GATHER FACTS FROM CISCO ROUTER
    hosts: ios_xe
    connection: network_cli
    gather_facts: no

    tasks:
      - name: BASIC CONFIG ROLE
        include_role:
          name: basic-config