---
  - name: GATHER FACTS FROM CISCO ROUTER
    hosts: ios_xe
    connection: network_cli
    gather_facts: no

    tasks:
      - name: GATHER FACTS
        ios_facts:
        register: output

      - name: VIEW DATA
        debug:
          var: output